create procedure "Decisioning_Procs"."Regression_Contact_Propensity"( 
  in "TA_Forecast_Model" varchar(50) default null,
  in "Value_Forecast_Model" varchar(50) default null,
  in "Src_Table" varchar(100) default 'Forecast_Loop_Table',
  in "Proc_Function" varchar(100) default 'Scoring',
  in "Trgt_View_Name" varchar(100) default "substr"("Src_Table","patindex"('%.%',"Src_Table")+1,"len"("Src_Table")-"patindex"('%.%',"Src_Table")) || '_Regr_View',
  in "Trgt_TA_Score_Field" varchar(100) default 'pred_TA_Call_Cust_rate',
  in "Trgt_Value_Score_Field" varchar(100) default 'pred_Value_Call_Cust_rate' ) 
sql security invoker
begin
  declare "TA_Coeff_SQL" long varchar;
  declare "TA_Seasonality_SQL" long varchar;
  declare "TA_Propensity_SQL" long varchar;
  declare "Value_Coeff_SQL" long varchar;
  declare "Value_Propensity_SQL" long varchar;
  declare "Dynamic_SQL" long varchar;
  declare "Loop_Num" integer;
  declare "Var_Num" integer;
  declare "Var_Name" varchar(100);
  declare "Var_Coeff" numeric(10,5);
  if "TA_Forecast_Model" is not null then
    drop table if exists #TA_Regression_Coefficients;
    select distinct "Variable"
      into #TA_Regression_Coefficients
      from "Decisioning"."FORECAST_Propensity_Coeffs"
      where "Metric" = 'TA' and "Forecast_Model" = "TA_Forecast_Model";
    set "TA_Coeff_SQL" = '';
    set "TA_Seasonality_SQL" = '';
    set "TA_Propensity_SQL" = 'Case when DTV_Status_Code != ''AC'' then 0 else ';
    set "Loop_Num" = 1;
    while "Loop_Num" <= (select "count"() from #TA_Regression_Coefficients) loop
      set "TA_Coeff_SQL" = "TA_Coeff_SQL" || ',Case when DTV_Status_Code = ''AC'' then cpv_TA."a_' || (select "Variable" from #TA_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") || '"'
         || ' else 0 end as "TA_Coeff:' || (select "Variable" from #TA_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") || '"';
      set "TA_Seasonality_SQL" = "TA_Seasonality_SQL" || case when(select "Variable" from #TA_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") in( 'Intercept','is_on_Com_offer','is_on_tv_offer' ) 
        and "Trgt_View_Name" <> 'Actuals' then
          ',Case when DTV_Status_Code = ''AC'' then seasonality."TA_Adj: ' || (select "Variable" from #TA_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") || '"'
           || 'else 0 end as "TA_Adj: ' || (select "Variable" from #TA_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") || '"'
        end;
      set "TA_Propensity_SQL" = "TA_Propensity_SQL" || '"' || (select "Variable" from #TA_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") || '"'
         || ' * '
         || '(  "TA_Coeff:' || (select "Variable" from #TA_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") || '"'
         || case when(select "Variable" from #TA_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") in( 'Intercept','is_on_com_offer','is_on_tv_offer' ) then
          ' * (1 + "TA_Adj: ' || (select "Variable" from #TA_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") || '")'
        end
         || ')'
         || "char"(13)
         || '+';
      set "Loop_Num" = "Loop_Num"+1
    end loop;
    set "TA_Propensity_SQL" = ',' || "Substr"("TA_Propensity_SQL",1,"len"("TA_Propensity_SQL")-1) || ' end as TA_Propensity '
  end if;
  if "Value_Forecast_Model" is not null then
    drop table if exists #Value_Regression_Coefficients;
    select distinct "Variable"
      into #Value_Regression_Coefficients
      from "Decisioning"."FORECAST_Propensity_Coeffs"
      where "Metric" = 'Value Calls' and "Forecast_Model" = "Value_Forecast_Model";
    set "Value_Coeff_SQL" = '';
    set "Value_Propensity_SQL" = 'Case when DTV_Status_Code != ''AC'' then 0 else ';
    set "Loop_Num" = 1;
    while "Loop_Num" <= (select "count"() from #Value_Regression_Coefficients) loop
      set "Value_Coeff_SQL" = "Value_Coeff_SQL" || ',Case when DTV_Status_Code = ''AC'' then cpv_Value."a_' || (select "Variable" from #Value_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") || '"'
         || ' else 0 end as "Value_Coeff:' || (select "Variable" from #Value_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") || '"';
      set "Value_Seasonality_SQL" = "Value_Seasonality_SQL" || case when(select "Variable" from #Value_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") in( 'Intercept','Sports','Movies','Top Tier' ) 
        and "Trgt_View_Name" <> 'Actuals' then
          ',Case when DTV_Status_Code = ''AC'' then seasonality."Value_Adj: ' || (select "Variable" from #Value_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") || '"'
           || 'else 0 end as "Value_Adj: ' || (select "Variable" from #TA_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") || '"'
        end;
      set "Value_Propensity_SQL" = "Value_Propensity_SQL" || 'cpv_Value."a_' || (select "Variable" from #Value_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") || '"'
         || ' * '
         || '"' || (select "Variable" from #Value_Regression_Coefficients as "A" where "rowid"("A") = "Loop_Num") || '"'
         || '+';
      set "Loop_Num" = "Loop_Num"+1
    end loop;
    set "Value_Propensity_SQL" = ',' || "Substr"("Value_Propensity_SQL",1,"len"("Value_Propensity_SQL")-1) || ' end as Value_Propensity_Unadjusted '
  end if;
  execute immediate 'Drop view if exists ' || "Trgt_View_Name";
  set "Dynamic_SQL" = 'Create view ' || "Trgt_View_Name" || '  as Select a.*, ''' || "Proc_Function" || ''' as Proc_Function '
     || ',Case when Future_Dated_Offer_Intended_end_Dt_DTV > Coalesce(Curr_Offer_Intended_end_Dt_dtv,Cast(''1900-01-01'' as date)) then Future_Dated_Offer_Intended_end_Dt_DTV else Curr_Offer_Intended_end_Dt_dtv end as XXXX_Curr_Offer_Intended_end_Dt_dtv '
     || ',Case when Future_Dated_Offer_Intended_end_Dt_BB > Coalesce(Curr_Offer_Intended_end_Dt_BB,Cast(''1900-01-01'' as date)) then Future_Dated_Offer_Intended_end_Dt_BB else Curr_Offer_Intended_end_Dt_BB end as XXXX_Curr_Offer_Intended_end_Dt_BB '
     || case when "TA_Forecast_Model" is not null then "TA_Coeff_SQL" end
     || case when "TA_Forecast_Model" is not null then "TA_Seasonality_SQL" end
     || case when "Value_Forecast_Model" is not null then "Value_Coeff_SQL" end
     || ',Cast(365.0 as numeric(10,5)) as days_year '
     || ',Cast(30.0 as numeric(10,5)) as days_mnth '
     || ',Cast(7.0 as numeric(10,5)) as days_week '
     || ',Case when DTV_active=1 and XXXX_Curr_Offer_Intended_end_Dt_dtv is not null and  6*7 < XXXX_Curr_Offer_Intended_end_Dt_dtv - End_Date '
     || '        then ''A.Expiring 7+'' '
     || '  when  DTV_active=1 and XXXX_Curr_Offer_Intended_end_Dt_dtv is not null and XXXX_Curr_Offer_Intended_end_Dt_dtv - End_Date between 3*7 + 1 and 6*7 '
     || '        then ''B.Expiring 4-6'' '
     || '  when  DTV_active=1 and XXXX_Curr_Offer_Intended_end_Dt_dtv is not null and XXXX_Curr_Offer_Intended_end_Dt_dtv - End_Date between 1*7 + 1 and 3*7 '
     || '        then ''C.Expiring 2-3'' '
     || '  when  DTV_active=1 and XXXX_Curr_Offer_Intended_end_Dt_dtv is not null and  XXXX_Curr_Offer_Intended_end_Dt_dtv - End_Date between 1 and 7 '
     || '        then ''D.Expiring 1'' '
     || '  when  DTV_active=1 and XXXX_Curr_Offer_Intended_end_Dt_dtv is null and Prev_Offer_Actual_End_Dt_dtv is not  null and  End_Date - Prev_Offer_Actual_End_Dt_dtv between 0 and 6 '
     || '        then ''E.Expired 1'' '
     || '  when  DTV_active=1 and XXXX_Curr_Offer_Intended_end_Dt_dtv is null and Prev_Offer_Actual_End_Dt_dtv is not  null and  End_Date - Prev_Offer_Actual_End_Dt_dtv between 1 * 7 and 3*7-1 '
     || '        then ''F.Expired 2-3'' '
     || '  when  DTV_active=1 and XXXX_Curr_Offer_Intended_end_Dt_dtv is null and Prev_Offer_Actual_End_Dt_dtv is not  null and  End_Date - Prev_Offer_Actual_End_Dt_dtv between 3 * 7 and 6*7-1 '
     || '        then ''G.Expired 4-6'' '
     || '  when  DTV_active=1 and XXXX_Curr_Offer_Intended_end_Dt_dtv is null and Prev_Offer_Actual_End_Dt_dtv is not  null and End_Date - Prev_Offer_Actual_End_Dt_dtv between 6 * 7 and 52*7-1 '
     || '        then ''H.Expired 7+'' '
     || '  else ''I.No Offer'' '
     || '  end as dtv_offer_end_band '
     || ',Case when Sports_active=1 and Curr_Offer_Intended_end_Dt_Sports is not null and  6*7 < Curr_Offer_Intended_end_Dt_Sports - End_Date '
     || '        then ''A.Expiring 7+'' '
     || '  when  Sports_active=1 and Curr_Offer_Intended_end_Dt_Sports is not null and Curr_Offer_Intended_end_Dt_Sports - End_Date between 3*7 + 1 and 6*7 '
     || '        then ''B.Expiring 4-6'' '
     || '  when  Sports_active=1 and Curr_Offer_Intended_end_Dt_Sports is not null and Curr_Offer_Intended_end_Dt_Sports - End_Date between 1*7 + 1 and 3*7 '
     || '        then ''C.Expiring 2-3'' '
     || '  when  Sports_active=1 and Curr_Offer_Intended_end_Dt_Sports is not null and  Curr_Offer_Intended_end_Dt_Sports - End_Date between 1 and 7 '
     || '        then ''D.Expiring 1'' '
     || '  when  Sports_active=1 and Curr_Offer_Intended_end_Dt_Sports is null and Prev_Offer_Actual_End_Dt_Sports is not  null and  End_Date - Prev_Offer_Actual_End_Dt_Sports between 0 and 6 '
     || '        then ''E.Expired 1'' '
     || '  when  Sports_active=1 and Curr_Offer_Intended_end_Dt_Sports is null and Prev_Offer_Actual_End_Dt_Sports is not  null and  End_Date - Prev_Offer_Actual_End_Dt_Sports between 1 * 7 and 3*7-1 '
     || '        then ''F.Expired 2-3'' '
     || '  when  Sports_active=1 and Curr_Offer_Intended_end_Dt_Sports is null and Prev_Offer_Actual_End_Dt_Sports is not  null and  End_Date - Prev_Offer_Actual_End_Dt_Sports between 3 * 7 and 6*7-1 '
     || '        then ''G.Expired 4-6'' '
     || '  when  Sports_active=1 and Curr_Offer_Intended_end_Dt_Sports is null and Prev_Offer_Actual_End_Dt_Sports is not  null and End_Date - Prev_Offer_Actual_End_Dt_Sports between 6 * 7 and 52*7-1 '
     || '        then ''H.Expired 7+'' '
     || '  else ''I.No Offer'' '
     || '  end as Sports_offer_end_band '
     || ',Case when Movies_active=1 and Curr_Offer_Intended_end_Dt_Movies is not null and  6*7 < Curr_Offer_Intended_end_Dt_Movies - End_Date '
     || '        then ''A.Expiring 7+'' '
     || '  when  Movies_active=1 and Curr_Offer_Intended_end_Dt_Movies is not null and Curr_Offer_Intended_end_Dt_Movies - End_Date between 3*7 + 1 and 6*7 '
     || '        then ''B.Expiring 4-6'' '
     || '  when  Movies_active=1 and Curr_Offer_Intended_end_Dt_Movies is not null and Curr_Offer_Intended_end_Dt_Movies - End_Date between 1*7 + 1 and 3*7 '
     || '        then ''C.Expiring 2-3'' '
     || '  when  Movies_active=1 and Curr_Offer_Intended_end_Dt_Movies is not null and  Curr_Offer_Intended_end_Dt_Movies - End_Date between 1 and 7 '
     || '        then ''D.Expiring 1'' '
     || '  when  Movies_active=1 and Curr_Offer_Intended_end_Dt_Movies is null and Prev_Offer_Actual_End_Dt_Movies is not  null and  End_Date - Prev_Offer_Actual_End_Dt_Movies between 0 and 6 '
     || '        then ''E.Expired 1'' '
     || '  when  Movies_active=1 and Curr_Offer_Intended_end_Dt_Movies is null and Prev_Offer_Actual_End_Dt_Movies is not  null and  End_Date - Prev_Offer_Actual_End_Dt_Movies between 1 * 7 and 3*7-1 '
     || '        then ''F.Expired 2-3'' '
     || '  when  Movies_active=1 and Curr_Offer_Intended_end_Dt_Movies is null and Prev_Offer_Actual_End_Dt_Movies is not  null and  End_Date - Prev_Offer_Actual_End_Dt_Movies between 3 * 7 and 6*7-1 '
     || '        then ''G.Expired 4-6'' '
     || '  when  Movies_active=1 and Curr_Offer_Intended_end_Dt_Movies is null and Prev_Offer_Actual_End_Dt_Movies is not  null and End_Date - Prev_Offer_Actual_End_Dt_Movies between 6 * 7 and 52*7-1 '
     || '        then ''H.Expired 7+'' '
     || '  else ''I.No Offer'' '
     || '  end as Movies_offer_end_band '
     || ',Case when BB_active=1 and XXXX_Curr_Offer_Intended_end_Dt_BB is not null and  6*7 < XXXX_Curr_Offer_Intended_end_Dt_BB - End_Date '
     || '        then ''A.Expiring 7+'' '
     || '  when  BB_active=1 and XXXX_Curr_Offer_Intended_end_Dt_BB is not null and XXXX_Curr_Offer_Intended_end_Dt_BB - End_Date between 3*7 + 1 and 6*7 '
     || '        then ''B.Expiring 4-6'' '
     || ' when  BB_active=1 and XXXX_Curr_Offer_Intended_end_Dt_BB is not null and XXXX_Curr_Offer_Intended_end_Dt_BB - End_Date between 1*7 + 1 and 3*7 '
     || '        then ''C.Expiring 2-3'' '
     || '  when  BB_active=1 and XXXX_Curr_Offer_Intended_end_Dt_BB is not null and  XXXX_Curr_Offer_Intended_end_Dt_BB - End_Date between 1 and 7 '
     || '        then ''D.Expiring 1'' '
     || '  when  BB_active=1 and XXXX_Curr_Offer_Intended_end_Dt_BB is null and Prev_Offer_Actual_End_Dt_BB is not  null and  End_Date - Prev_Offer_Actual_End_Dt_BB between 0 and 6 '
     || '        then ''E.Expired 1'' '
     || '  when  BB_active=1 and XXXX_Curr_Offer_Intended_end_Dt_BB is null and Prev_Offer_Actual_End_Dt_BB is not  null and  End_Date - Prev_Offer_Actual_End_Dt_BB between 1 * 7 and 3*7-1 '
     || '        then ''F.Expired 2-3'' '
     || '  when  BB_active=1 and XXXX_Curr_Offer_Intended_end_Dt_BB is null and Prev_Offer_Actual_End_Dt_BB is not  null and  End_Date - Prev_Offer_Actual_End_Dt_BB between 3 * 7 and 6*7-1 '
     || '        then ''G.Expired 4-6'' '
     || '  when  BB_active=1 and XXXX_Curr_Offer_Intended_end_Dt_BB is null and Prev_Offer_Actual_End_Dt_BB is not  null and End_Date - Prev_Offer_Actual_End_Dt_BB between 6 * 7 and 52*7-1 '
     || '        then ''H.Expired 7+'' '
     || '  else ''I.No Offer'' '
     || '  end as BB_offer_end_band '
     || ',Case when LR_active=1 and Curr_Offer_Intended_end_Dt_LR is not null and  6*7 < Curr_Offer_Intended_end_Dt_LR - End_Date '
     || '        then ''A.Expiring 7+'' '
     || '     when  LR_active=1 and Curr_Offer_Intended_end_Dt_LR is not null and Curr_Offer_Intended_end_Dt_LR - End_Date between 3*7 + 1 and 6*7 '
     || '        then ''B.Expiring 4-6'' '
     || '  when  LR_active=1 and Curr_Offer_Intended_end_Dt_LR is not null and Curr_Offer_Intended_end_Dt_LR - End_Date between 1*7 + 1 and 3*7 '
     || '        then ''C.Expiring 2-3'' '
     || '  when  LR_active=1 and Curr_Offer_Intended_end_Dt_LR is not null and  Curr_Offer_Intended_end_Dt_LR - End_Date between 1 and 7 '
     || '        then ''D.Expiring 1'' '
     || '  when  LR_active=1 and Curr_Offer_Intended_end_Dt_LR is null and Prev_Offer_Actual_End_Dt_LR is not  null and  End_Date - Prev_Offer_Actual_End_Dt_LR between 0 and 6 '
     || '        then ''E.Expired 1'' '
     || '  when  LR_active=1 and Curr_Offer_Intended_end_Dt_LR is null and Prev_Offer_Actual_End_Dt_LR is not  null and  End_Date - Prev_Offer_Actual_End_Dt_LR between 1 * 7 and 3*7-1 '
     || '        then ''F.Expired 2-3'' '
     || '  when  LR_active=1 and Curr_Offer_Intended_end_Dt_LR is null and Prev_Offer_Actual_End_Dt_LR is not  null and  End_Date - Prev_Offer_Actual_End_Dt_LR between 3 * 7 and 6*7-1 '
     || '        then ''G.Expired 4-6'' '
     || '  when  LR_active=1 and Curr_Offer_Intended_end_Dt_LR is null and Prev_Offer_Actual_End_Dt_LR is not  null and End_Date - Prev_Offer_Actual_End_Dt_LR between 6 * 7 and 52*7-1 '
     || '        then ''H.Expired 7+'' '
     || '  else ''I.No Offer'' '
     || '  end as LR_offer_end_band '
     || ',Case when Future_Dated_Offer_Start_Dt_DTV > end_date then ''A.Expiring 7+'' '
     || '     when dtv_offer_end_band<=sports_offer_end_band and dtv_offer_end_band<=movies_offer_end_band then dtv_offer_end_band '
     || '     when movies_offer_end_band <= dtv_offer_end_band and movies_offer_end_band <= sports_offer_end_band then movies_offer_end_band '
     || '     when sports_offer_end_band <= dtv_offer_end_band and sports_offer_end_band <= movies_offer_end_band then sports_offer_end_band '
     || 'end as tv_offer_end_band '
     || ',Case when Future_Dated_Offer_Start_Dt_BB > end_date then ''A.Expiring 7+'' '
     || '      when bb_offer_end_band<=lr_offer_end_band then bb_offer_end_band '
     || '      else lr_offer_end_band '
     || 'end as Com_offer_end_band '
     || ', Case when dtv_offer_end_band = ''B.Expiring 4-6'' then Coalesce(-Curr_Offer_Amount_DTV,0)/10 else 0 end as DTV_offer_ending_in_4_6_wk_depth '
     || ', Case when dtv_offer_end_band = ''C.Expiring 2-3'' then Coalesce(-Curr_Offer_Amount_DTV,0)/10 else 0 end as DTV_offer_ending_in_2_3_wk_depth '
     || ', Case when dtv_offer_end_band = ''D.Expiring 1'' then Coalesce(-Curr_Offer_Amount_DTV,0)/10 else 0 end as DTV_offer_ending_in_1_wk_depth '
     || ', Case when dtv_offer_end_band = ''E.Expired 1'' then Coalesce(-Prev_Offer_Amount_DTV,0)/10 else 0 end as DTV_offer_ended_in_1_wk_depth '
     || ', Case when dtv_offer_end_band = ''F.Expired 2-3'' then Coalesce(-Prev_Offer_Amount_DTV,0)/10 else 0 end as DTV_offer_ended_in_2_3_wk_depth '
     || ', Case when dtv_offer_end_band = ''G.Expired 4-6'' then Coalesce(-Prev_Offer_Amount_DTV,0)/10 else 0 end as DTV_offer_ended_in_4_6_wk_depth '
     || ', Case when sports_offer_end_band = ''B.Expiring 4-6'' then Coalesce(-Curr_Offer_Amount_sports,0)/10 else 0 end as sp_offer_ending_in_4_6_wk_depth '
     || ', Case when sports_offer_end_band = ''C.Expiring 2-3'' then Coalesce(-Curr_Offer_Amount_sports,0)/10 else 0 end as sp_offer_ending_in_2_3_wk_depth '
     || ', Case when sports_offer_end_band = ''D.Expiring 1'' then Coalesce(-Curr_Offer_Amount_sports,0)/10 else 0 end as sp_offer_ending_in_1_wk_depth '
     || ', Case when sports_offer_end_band = ''E.Expired 1'' then Coalesce(-Prev_Offer_Amount_sports,0)/10 else 0 end as sp_offer_ended_in_1_wk_depth '
     || ', Case when sports_offer_end_band = ''F.Expired 2-3'' then Coalesce(-Prev_Offer_Amount_sports,0)/10 else 0 end as sp_offer_ended_in_2_3_wk_depth '
     || ', Case when sports_offer_end_band = ''G.Expired 4-6'' then Coalesce(-Prev_Offer_Amount_sports,0)/10 else 0 end as sp_offer_ended_in_4_6_wk_depth '
     || ', Case when movies_offer_end_band = ''B.Expiring 4-6'' then Coalesce(-Curr_Offer_Amount_movies,0)/10 else 0 end as mv_offer_ending_in_4_6_wk_depth '
     || ', Case when movies_offer_end_band = ''C.Expiring 2-3'' then Coalesce(-Curr_Offer_Amount_movies,0)/10 else 0 end as mv_offer_ending_in_2_3_wk_depth '
     || ', Case when movies_offer_end_band = ''D.Expiring 1'' then Coalesce(-Curr_Offer_Amount_movies,0)/10 else 0 end as mv_offer_ending_in_1_wk_depth '
     || ', Case when movies_offer_end_band = ''E.Expired 1'' then Coalesce(-Prev_Offer_Amount_movies,0)/10 else 0 end as mv_offer_ended_in_1_wk_depth '
     || ', Case when movies_offer_end_band = ''F.Expired 2-3'' then Coalesce(-Prev_Offer_Amount_movies,0)/10 else 0 end as mv_offer_ended_in_2_3_wk_depth '
     || ', Case when movies_offer_end_band = ''G.Expired 4-6'' then Coalesce(-Prev_Offer_Amount_movies,0)/10 else 0 end as mv_offer_ended_in_4_6_wk_depth '
     || ', Case when bb_offer_end_band = ''B.Expiring 4-6'' then Coalesce(-Curr_Offer_Amount_bb,0)/10 else 0 end as bb_offer_ending_in_4_6_wk_depth '
     || ', Case when bb_offer_end_band = ''C.Expiring 2-3'' then Coalesce(-Curr_Offer_Amount_bb,0)/10 else 0 end as bb_offer_ending_in_2_3_wk_depth '
     || ', Case when bb_offer_end_band = ''D.Expiring 1'' then Coalesce(-Curr_Offer_Amount_bb,0)/10 else 0 end as bb_offer_ending_in_1_wk_depth '
     || ', Case when bb_offer_end_band = ''E.Expired 1'' then Coalesce(-Prev_Offer_Amount_bb,0)/10 else 0 end as bb_offer_ended_in_1_wk_depth '
     || ', Case when bb_offer_end_band = ''F.Expired 2-3'' then Coalesce(-Prev_Offer_Amount_bb,0)/10 else 0 end as bb_offer_ended_in_2_3_wk_depth '
     || ', Case when bb_offer_end_band = ''G.Expired 4-6'' then Coalesce(-Prev_Offer_Amount_bb,0)/10 else 0 end as bb_offer_ended_in_4_6_wk_depth '
     || ', Case when lr_offer_end_band = ''B.Expiring 4-6'' then Coalesce(-Curr_Offer_Amount_lr,0)/10 else 0 end as lr_offer_ending_in_4_6_wk_depth '
     || ', Case when lr_offer_end_band = ''C.Expiring 2-3'' then Coalesce(-Curr_Offer_Amount_lr,0)/10 else 0 end as lr_offer_ending_in_2_3_wk_depth '
     || ', Case when lr_offer_end_band = ''D.Expiring 1'' then Coalesce(-Curr_Offer_Amount_lr,0)/10 else 0 end as lr_offer_ending_in_1_wk_depth '
     || ', Case when lr_offer_end_band = ''E.Expired 1'' then Coalesce(-Prev_Offer_Amount_lr,0)/10 else 0 end as lr_offer_ended_in_1_wk_depth '
     || ', Case when lr_offer_end_band = ''F.Expired 2-3'' then Coalesce(-Prev_Offer_Amount_lr,0)/10 else 0 end as lr_offer_ended_in_2_3_wk_depth '
     || ', Case when lr_offer_end_band = ''G.Expired 4-6'' then Coalesce(-Prev_Offer_Amount_lr,0)/10 else 0 end as lr_offer_ended_in_4_6_wk_depth '
     || ', Case when dtv_offer_end_band    =  tv_offer_end_band and tv_offer_end_band = ''B.Expiring 4-6''                                                 then Coalesce(-Curr_Offer_Amount_DTV,0)/10 else 0 end '
     || '+ Case when sports_offer_end_band =  tv_offer_end_band and tv_offer_end_band = ''B.Expiring 4-6''  and curr_offer_id_sports != curr_offer_id_DTV  then Coalesce(-Curr_Offer_Amount_Sports,0)/10 else 0 end '
     || '+ Case when movies_offer_end_band =  tv_offer_end_band and tv_offer_end_band = ''B.Expiring 4-6''  and curr_offer_id_movies != curr_offer_id_DTV  then Coalesce(-Curr_Offer_Amount_Movies,0)/10 else 0 end '
     || 'as TV_offer_ending_in_4_6_wk_depth '
     || ', Case when dtv_offer_end_band    =  tv_offer_end_band and tv_offer_end_band = ''C.Expiring 2-3''                                                 then Coalesce(-Curr_Offer_Amount_DTV,0)/10 else 0 end '
     || '+ Case when sports_offer_end_band =  tv_offer_end_band and tv_offer_end_band = ''C.Expiring 2-3''  and curr_offer_id_sports != curr_offer_id_DTV  then Coalesce(-Curr_Offer_Amount_Sports,0)/10 else 0 end '
     || '+ Case when movies_offer_end_band =  tv_offer_end_band and tv_offer_end_band = ''C.Expiring 2-3''  and curr_offer_id_movies != curr_offer_id_DTV  then Coalesce(-Curr_Offer_Amount_Movies,0)/10 else 0 end '
     || 'as TV_offer_ending_in_2_3_wk_depth '
     || ', Case when dtv_offer_end_band    =  tv_offer_end_band and tv_offer_end_band = ''D.Expiring 1''                                                 then Coalesce(-Curr_Offer_Amount_DTV,0)/10 else 0 end '
     || '+ Case when sports_offer_end_band =  tv_offer_end_band and tv_offer_end_band = ''D.Expiring 1''  and curr_offer_id_sports != curr_offer_id_DTV  then Coalesce(-Curr_Offer_Amount_Sports,0)/10 else 0 end '
     || '+ Case when movies_offer_end_band =  tv_offer_end_band and tv_offer_end_band = ''D.Expiring 1''  and curr_offer_id_movies != curr_offer_id_DTV  then Coalesce(-Curr_Offer_Amount_Movies,0)/10 else 0 end '
     || 'as TV_offer_ending_in_1_wk_depth '
     || ', Case when dtv_offer_end_band    =  tv_offer_end_band and tv_offer_end_band = ''E.Expired 1''                                                 then Coalesce(-Prev_Offer_Amount_DTV,0)/10 else 0 end '
     || '+ Case when sports_offer_end_band =  tv_offer_end_band and tv_offer_end_band = ''E.Expired 1''  and Prev_offer_id_sports != Prev_offer_id_DTV  then Coalesce(-Prev_Offer_Amount_Sports,0)/10 else 0 end '
     || '+ Case when movies_offer_end_band =  tv_offer_end_band and tv_offer_end_band = ''E.Expired 1''  and Prev_offer_id_movies != Prev_offer_id_DTV  then Coalesce(-Prev_Offer_Amount_Movies,0)/10 else 0 end '
     || 'as TV_offer_ended_in_1_wk_depth '
     || ', Case when dtv_offer_end_band    =  tv_offer_end_band and tv_offer_end_band = ''F.Expired 2-3''                                                 then Coalesce(-Prev_Offer_Amount_DTV,0)/10 else 0 end '
     || '+ Case when sports_offer_end_band =  tv_offer_end_band and tv_offer_end_band = ''F.Expired 2-3''  and Prev_offer_id_sports != Prev_offer_id_DTV  then Coalesce(-Prev_Offer_Amount_Sports,0)/10 else 0 end '
     || '+ Case when movies_offer_end_band =  tv_offer_end_band and tv_offer_end_band = ''F.Expired 2-3''  and Prev_offer_id_movies != Prev_offer_id_DTV  then Coalesce(-Prev_Offer_Amount_Movies,0)/10 else 0 end '
     || 'as TV_offer_ended_in_2_3_wk_depth '
     || ', Case when dtv_offer_end_band    =  tv_offer_end_band and tv_offer_end_band = ''G.Expired 4-6''                                                 then Coalesce(-Prev_Offer_Amount_DTV,0)/10 else 0 end '
     || '+ Case when sports_offer_end_band =  tv_offer_end_band and tv_offer_end_band = ''G.Expired 4-6''  and Prev_offer_id_sports != Prev_offer_id_DTV  then Coalesce(-Prev_Offer_Amount_Sports,0)/10 else 0 end '
     || '+ Case when movies_offer_end_band =  tv_offer_end_band and tv_offer_end_band = ''G.Expired 4-6''  and Prev_offer_id_movies != Prev_offer_id_DTV  then Coalesce(-Prev_Offer_Amount_Movies,0)/10 else 0 end '
     || 'as TV_offer_ended_in_4_6_wk_depth '
     || ', Case when bb_offer_end_band    =  com_offer_end_band and com_offer_end_band = ''B.Expiring 4-6''                                                 then Coalesce(-Curr_Offer_Amount_bb,0)/10 else 0 end '
     || '+ Case when lr_offer_end_band =     com_offer_end_band and com_offer_end_band = ''B.Expiring 4-6''  and curr_offer_id_lr != curr_offer_id_bb  then Coalesce(-Curr_Offer_Amount_lr,0)/10 else 0 end '
     || 'as Com_offer_ending_in_4_6_wk_depth '
     || ', Case when bb_offer_end_band    =  com_offer_end_band and com_offer_end_band = ''C.Expiring 2-3''                                                 then Coalesce(-Curr_Offer_Amount_bb,0)/10 else 0 end '
     || '+ Case when lr_offer_end_band =  com_offer_end_band and com_offer_end_band = ''C.Expiring 2-3''  and curr_offer_id_lr != curr_offer_id_bb  then Coalesce(-Curr_Offer_Amount_lr,0)/10 else 0 end '
     || 'as Com_offer_ending_in_2_3_wk_depth '
     || ', Case when bb_offer_end_band    =  com_offer_end_band and com_offer_end_band = ''D.Expiring 1''                                                 then Coalesce(-Curr_Offer_Amount_bb,0)/10 else 0 end '
     || '+ Case when lr_offer_end_band =  com_offer_end_band and com_offer_end_band = ''D.Expiring 1''  and curr_offer_id_lr != curr_offer_id_bb  then Coalesce(-Curr_Offer_Amount_lr,0)/10 else 0 end '
     || 'as Com_offer_ending_in_1_wk_depth '
     || ', Case when bb_offer_end_band    =  com_offer_end_band and com_offer_end_band = ''E.Expired 1''                                                 then Coalesce(-Prev_Offer_Amount_bb,0)/10 else 0 end '
     || '+ Case when lr_offer_end_band =  com_offer_end_band and com_offer_end_band = ''E.Expired 1''  and Prev_offer_id_lr != Prev_offer_id_bb  then Coalesce(-Prev_Offer_Amount_lr,0)/10 else 0 end '
     || 'as Com_offer_ended_in_1_wk_depth '
     || ', Case when bb_offer_end_band    =  com_offer_end_band and com_offer_end_band = ''F.Expired 2-3''                                                 then Coalesce(-Prev_Offer_Amount_bb,0)/10 else 0 end '
     || '+ Case when lr_offer_end_band =  com_offer_end_band and com_offer_end_band = ''F.Expired 2-3''  and Prev_offer_id_lr != Prev_offer_id_bb  then Coalesce(-Prev_Offer_Amount_lr,0)/10 else 0 end '
     || 'as Com_offer_ended_in_2_3_wk_depth '
     || ', Case when bb_offer_end_band    =  com_offer_end_band and com_offer_end_band = ''G.Expired 4-6''                                                 then Coalesce(-Prev_Offer_Amount_bb,0)/10 else 0 end '
     || '+ Case when lr_offer_end_band =  com_offer_end_band and com_offer_end_band = ''G.Expired 4-6''  and Prev_offer_id_lr != Prev_offer_id_bb  then Coalesce(-Prev_Offer_Amount_lr,0)/10 else 0 end '
     || 'as Com_offer_ended_in_4_6_wk_depth '
     || ', Cast(0 as tinyint) as future_dated_dtv_offer '
     || ',Case when dtv_offer_end_band=''A.Expiring 7+'' then 1 else 0 end as is_on_dtv_offer '
     || ',Case when dtv_offer_end_band=''H.Expired 7+''  then 1 else 0 end as was_on_dtv_offer '
     || ', Cast(0 as tinyint) as future_dated_bb_offer '
     || ',Case when bb_offer_end_band=''A.Expiring 7+'' then 1 else 0 end as is_on_bb_offer '
     || ',Case when bb_offer_end_band=''H.Expired 7+'' then 1 else 0 end as was_on_bb_offer '
     || ', Cast(0 as tinyint) as future_dated_lr_offer '
     || ',Case when lr_offer_end_band=''A.Expiring 7+'' then 1 else 0 end as is_on_lr_offer '
     || ',Case when lr_offer_end_band=''H.Expired 7+'' then 1 else 0 end as was_on_lr_offer '
     || ',Case when tv_offer_end_band=''A.Expiring 7+'' then 1 else 0 end as is_on_tv_offer '
     || ',Case when com_offer_end_band=''A.Expiring 7+'' then 1 else 0 end as is_on_com_offer '
     || ',Case when tv_offer_end_band=''H.Expired 7+''  then 1 else 0 end as was_on_tv_offer '
     || ',Case when com_offer_end_band=''H.Expired 7+''  then 1 else 0 end as was_on_com_offer '
     || ', Cast(0 as tinyint) as future_dated_com_offer '
     || ', Cast(0 as tinyint) as future_dated_tv_offer '
     || ',Case when  DTV_active=1 and DTV_Curr_Contract_Intended_End_Dt is not null and 5*7 < DTV_Curr_Contract_Intended_End_Dt - end_date then ''A.Expiring 6+'' '
     || '      when  DTV_active=1 and DTV_Curr_Contract_Intended_End_Dt is not null and DTV_Curr_Contract_Intended_End_Dt  - end_date between 3*7 + 1 and  5*7 then ''B.Expiring 4-5'' '
     || '      when  DTV_active=1 and DTV_Curr_Contract_Intended_End_Dt is not null and DTV_Curr_Contract_Intended_End_Dt  - end_date between 1*7 + 1 and  3*7 then ''C.Expiring 2-3'' '
     || '      when  DTV_active=1 and DTV_Curr_Contract_Intended_End_Dt is not null and DTV_Curr_Contract_Intended_End_Dt  - end_date <=  1*7 then ''D.Expiring 1'' '
     || '      when  DTV_active=1 and DTV_Curr_Contract_Intended_End_Dt is null  and DTV_Prev_Contract_Actual_End_Dt is not null '
     || '            and end_date - DTV_Prev_Contract_Actual_End_Dt between 0 and 7 - 1 then ''E.Expired 1'' '
     || '      when  DTV_active=1 and DTV_Curr_Contract_Intended_End_Dt is null  and DTV_Prev_Contract_Actual_End_Dt is not null '
     || '            and end_date - DTV_Prev_Contract_Actual_End_Dt between 1*7 and 5*7 - 1 then ''F.Expired 2-5'' '
     || '      when  DTV_active=1 and DTV_Curr_Contract_Intended_End_Dt is null  and DTV_Prev_Contract_Actual_End_Dt is not null '
     || '            and end_date - DTV_Prev_Contract_Actual_End_Dt between 5*7 and 8*7 - 1  then ''G.Expired 6-8'' '
     || '      else ''H.No Contract'' '
     || 'end as DTV_contract_end_band '
     || ',Case when   BB_active=1 and BB_Curr_Contract_Intended_End_Dt is not null and 5*7 < BB_Curr_Contract_Intended_End_Dt - end_date then ''A.Expiring 6+'' '
     || '      when  BB_active=1 and BB_Curr_Contract_Intended_End_Dt is not null and BB_Curr_Contract_Intended_End_Dt  - end_date between 3*7 + 1 and  5*7 then ''B.Expiring 4-5'' '
     || '      when  BB_active=1 and BB_Curr_Contract_Intended_End_Dt is not null and BB_Curr_Contract_Intended_End_Dt  - end_date between 1*7 + 1 and  3*7 then ''C.Expiring 2-3'' '
     || '      when  BB_active=1 and BB_Curr_Contract_Intended_End_Dt is not null and BB_Curr_Contract_Intended_End_Dt  - end_date <=  1*7 then ''D.Expiring 1'' '
     || '      when  BB_active=1 and BB_Curr_Contract_Intended_End_Dt is null  and BB_Prev_Contract_Actual_End_Dt is not null '
     || '            and end_date - BB_Prev_Contract_Actual_End_Dt between 0 and 7 - 1 then ''E.Expired 1'' '
     || '      when  BB_active=1 and BB_Curr_Contract_Intended_End_Dt is null  and BB_Prev_Contract_Actual_End_Dt is not null '
     || '            and end_date - BB_Prev_Contract_Actual_End_Dt between 1*7 and 5*7 - 1 then ''F.Expired 2-5'' '
     || '      when  BB_active=1 and BB_Curr_Contract_Intended_End_Dt is null  and BB_Prev_Contract_Actual_End_Dt is not null '
     || '            and end_date - BB_Prev_Contract_Actual_End_Dt between 5*7 and 8*7 - 1  then ''G.Expired 6-8'' '
     || '      else ''H.No Contract'' '
     || 'end as BB_contract_end_band '
     || ',(case when DTV_Curr_Contract_Start_Dt is not null then floor(DATEDIFF(DAY,DTV_Curr_Contract_Start_Dt,end_date)/days_week) end) as time_since_contract_start_dtv_weeks '
     || ' ,case '
     || '   when  Cast(end_date as integer)  < Cast(DTV_Last_Activation_Dt as integer)                          then ''New'' '
     || '   when  Cast(end_date as integer)  - Cast(DTV_Last_Activation_Dt as integer) <  round(365/12*1,0)     then ''M01'' '
     || '   when  Cast(end_date as integer)  - Cast(DTV_Last_Activation_Dt as integer) <  round(365/12*10,0)    then ''M10'' '
     || '   when  Cast(end_date as integer)  - Cast(DTV_Last_Activation_Dt as integer) <  round(365/12*14,0)    then ''M14'' '
     || '   when  Cast(end_date as integer)  - Cast(DTV_Last_Activation_Dt as integer) <  round(365/12*2*12,0)  then ''M24'' '
     || '   when  Cast(end_date as integer)  - Cast(DTV_Last_Activation_Dt as integer) <  round(365/12*3*12,0)  then ''Y03'' '
     || '   when  Cast(end_date as integer)  - Cast(DTV_Last_Activation_Dt as integer) <  round(365/12*5*12,0)  then ''Y05'' '
     || '   when  Cast(end_date as integer)  - Cast(DTV_Last_Activation_Dt as integer) >=  round(365/12*5*12,0) then ''Y05+'' '
     || ' end as Regr_DTV_Tenure '
     || ' ,Case when Regr_DTV_Tenure = ''M01'' then 1 else 0 end as "DTV_Tenure M01" '
     || ' ,Case when Regr_DTV_Tenure = ''M10'' then 1 else 0 end as "DTV_Tenure M10" '
     || ' ,Case when Regr_DTV_Tenure = ''M14'' then 1 else 0 end as "DTV_Tenure M14" '
     || ' ,Case when Regr_DTV_Tenure = ''M24'' then 1 else 0 end as "DTV_Tenure M24" '
     || ' ,Case when Regr_DTV_Tenure = ''Y03'' then 1 else 0 end as "DTV_Tenure Y03" '
     || ' ,Case when Regr_DTV_Tenure = ''Y05'' then 1 else 0 end as "DTV_Tenure Y05" '
     || ' ,Case when Regr_DTV_Tenure = ''Y05+'' then 1 else 0 end as "DTV_Tenure Y05+" '
     || ',(case when DTV_Last_Activation_Dt is not null then floor(DATEDIFF(DAY,DTV_Last_Activation_Dt,end_date)/days_mnth) end) as dtv_tenure_mnths '
     || ',Case   when  DTV_active=1 and DTV_Last_Activation_Dt is not null and 0 =  dtv_tenure_mnths   then  ''A.0'' '
     || '        when  DTV_active=1 and DTV_Last_Activation_Dt is not null and dtv_tenure_mnths between 1  and 9 then  ''B.1-9'' '
     || '        when  DTV_active=1 and DTV_Last_Activation_Dt is not null and dtv_tenure_mnths between 10 and 12  then  ''C.10-12'' '
     || '        else ''H.None'' '
     || ' end as mnths_DTV_tenure_band '
     || ',(case when BB_Last_Activation_Dt is not null then floor(DATEDIFF(DAY,BB_Last_Activation_Dt,end_date)/days_mnth) end) as BB_tenure_mnths '
     || ',Case   when  BB_active=1 and BB_Last_Activation_Dt is not null and 0 =  BB_tenure_mnths   then  ''A.0'' '
     || '        when  BB_active=1 and BB_Last_Activation_Dt is not null and BB_tenure_mnths between 1 and 9 then  ''B.1-9'' '
     || '        when  BB_active=1 and BB_Last_Activation_Dt is not null and BB_tenure_mnths between 10 and 12  then  ''C.10-12'' '
     || '        else ''H.None'' '
     || 'end as mnths_BB_tenure_band '
     || ',Case when last_TA_dt is not null then floor((end_date-last_TA_dt)/7) else 0 end as ta_call_recency_weeks '
     || ',(case when last_TA_dt is not null then floor(DATEDIFF(DAY,last_TA_dt,end_date)/days_week) end) as time_since_last_ta_weeks '
     || ',Case when   last_TA_dt is not null and  0 = ta_call_recency_weeks  and '
     || '        not(last_Offer_applied_Dt_dtv-last_ta_dt between 0 and 1 or last_Offer_applied_Dt_bb-last_ta_dt between 0 and 1) '
     || '     then ''A.0 NO'' '
     || '     when  last_TA_dt is not null and  0 = ta_call_recency_weeks  and '
     || '        (last_Offer_applied_Dt_dtv-last_ta_dt between 0 and 1 or last_Offer_applied_Dt_bb-last_ta_dt between 0 and 1) '
     || '     then ''B.0 OO'' '
     || '     when  last_TA_dt is not null and  1 = ta_call_recency_weeks '
     || '     then ''C.1'' '
     || '     when  last_TA_dt is not null and  ta_call_recency_weeks between 2 and  3 '
     || '     then ''D.2-3'' '
     || '     when  last_TA_dt is null  '
     || '     then ''E.None'' '
     || '     else ''F.Others'' '
     || 'end as ta_call_recency_in_week '
     || ',case when last_TA_dt is null then 1 else 0 end as ta_call_recency_in_week_No_call '
     || ',Case when last_Value_Call_dt is not null then floor((end_date-last_Value_Call_dt)/7) else 0 end as value_call_recency_weeks '
     || ',log(1+TAs_in_last_12m) as value_call_recency_weeks_lg '
     || ',Case when   last_Value_Call_dt is not null and  0 = value_call_recency_weeks  and '
     || '        not(last_Offer_applied_Dt_dtv-last_Value_Call_dt between 0 and 1 or last_Offer_applied_Dt_bb-last_Value_Call_dt between 0 and 1) '
     || '     then ''A.0 NO'' '
     || '     when  last_Value_Call_dt is not null and  0 = value_call_recency_weeks  and '
     || '        (last_Offer_applied_Dt_dtv-last_Value_Call_dt between 0 and 1 or last_Offer_applied_Dt_bb-last_Value_Call_dt between 0 and 1) '
     || '     then ''B.0 OO'' '
     || '     when  last_Value_Call_dt is not null and  1 = value_call_recency_weeks '
     || '     then ''C.1'' '
     || '     when  last_Value_Call_dt is not null and  value_call_recency_weeks between 2 and  3 '
     || '     then ''D.2-3'' '
     || '     when last_Value_Call_dt is null '
     || '     then ''E.No Prev Call'' '
     || '     else ''F.Others'' '
     || 'end as value_call_recency_in_week '
     || ',case when last_Value_Call_dt is null then 1 else 0 end as value_call_recency_in_week_No_call '
     || ',Case when value_call_recency_in_week = ''A.0 NO'' then 1 else 0 end as  "value_call_recency_in_week A.0 NO" '
     || ',Case when value_call_recency_in_week = ''B.0 OO'' then 1 else 0 end as  "value_call_recency_in_week B.0 OO" '
     || ',Case when value_call_recency_in_week = ''C.1'' then 1 else 0 end as  "value_call_recency_in_week C.1" '
     || ',Case when value_call_recency_in_week = ''D.2-3'' then 1 else 0 end as  "value_call_recency_in_week D.2-3" '
     || ',Case when Value_call_recency_in_week = ''E.No Prev Call'' then 1 else 0 end as "Value_call_recency_in_week E.No Prev Call" '
     || ',Case when Value_call_recency_in_week = ''F.Others'' then 1 else 0 end as "Value_call_recency_in_week F.Others" '
     || ',Case when Sports_Active > 0 and Movies_Active > 0 then ''Top Tier'' '
     || '      when Sports_Active > 0                       then ''Sports'' '
     || '      when Movies_Active > 0                       then ''Movies'' '
     || '      when DTV_Active > 0                          then ''Basic'' '
     || ' end as Regr_Prems_Product_Holding '
     || ',1 as Intercept '
     || ',  (case when bb_active=1 and BB_Last_Activation_Dt is not null then floor(DATEDIFF(DAY,BB_Last_Activation_Dt,end_date)/days_year) end) as bb_tenure_yrs '
     || ',(case when dtv_active=1 and DTV_Last_Activation_Dt is not null then floor(DATEDIFF(DAY,DTV_Last_Activation_Dt,end_date)/days_year) end) as DTV_tenure_yrs '
     || ',  log(1+(case when DTV_PCs_In_Last_180D is null then 0 else DTV_PCs_In_Last_180D end)) as DTV_PCs_In_Last_180D_lg '
     || ',  log(1+TAs_in_last_12m) as TAs_in_last_12m_lg '
     || ',  (case when TAs_in_last_12m=0 and (last_TA_dt is not null and  60 <= time_since_last_ta_weeks) '
     || '                                         then log(1+TAs_in_last_36m) else 0 end) as TAs_in_last_36m_lg '
     || ',  log(1+(case when dtv_tenure_yrs<=20 then dtv_tenure_yrs else 20 end)) as dtv_tenure_yrs_lg '
     || ',  log(1+Offers_Applied_Lst_90D_DTV) as Offers_Applied_Lst_90D_DTV_lg '
     || ',case when dtv_tenure_mnths = 0 then 1 else 0 end as mnths_dtv_tenure_band_0 '
     || ',case when dtv_tenure_mnths between 1 and 9 then 1 else 0 end as  mnths_dtv_tenure_band_1_9 '
     || ',case when dtv_tenure_mnths between 10 and 12  then 1 else 0 end as  mnths_dtv_tenure_band_10_12 '
     || ',case when bb_tenure_mnths = 0 then 1 else 0 end as mnths_bb_tenure_band_0 '
     || ',case when bb_tenure_mnths between 1 and 9 then 1 else 0 end as  mnths_bb_tenure_band_1_9 '
     || ',case when bb_tenure_mnths between 10 and 12  then 1 else 0 end as  mnths_bb_tenure_band_10_12 '
     || ',case when h_age_coarse in (''18-25'',''26-35'') then 1 else 0 end as age_band_18_35 '
     || ',case when h_age_coarse=''66+'' then 1 else 0 end as  age_band_66_plus '
     || ',(case when bb_active=1 and bb_product_holding like ''%Fibre%'' then 1 else 0 end) as "bb_holding A.FIBRE" '
     || ',(case when bb_active=1 and bb_product_holding not like ''%Fibre%'' then 1 else 0 end) as "bb_holding B.DSL" '
     || ',(case when bb_Active=0 and BB_Provider like ''%virgin%'' then 1 else 0 end) as "bb_holding C.Virgin" '
     || ',(case when bb_active=1 and bb_product_holding like ''%Fibre%'' then 1 else 0 end) as "value_bb_holding A.FIBRE" '
     || ',(case when bb_active=1 and bb_product_holding not like ''%Fibre%'' then 1 else 0 end) as "value_bb_holding B.DSL" '
     || ',Case when h_age_coarse in (''18-25'',''26-35'') then 1 else 0 end as "age_band A.18-35" '
     || ',Case when h_age_coarse=''66+''                then 1 else 0 end as  "age_band D.66+" '
     || ',Case when mnths_BB_tenure_band = ''A.0'' then 1 else 0 end as  "mnths_bb_tenure_band A.0" '
     || ',Case when mnths_BB_tenure_band = ''B.1-9'' then 1 else 0 end as  "mnths_bb_tenure_band B.1-9" '
     || ',Case when mnths_BB_tenure_band = ''C.10-12'' then 1 else 0 end as  "mnths_bb_tenure_band C.10-12" '
     || ',Case when mnths_DTV_tenure_band = ''A.0'' then 1 else 0 end as  "mnths_dtv_tenure_band A.0" '
     || ',Case when mnths_DTV_tenure_band = ''B.1-9'' then 1 else 0 end as  "mnths_dtv_tenure_band B.1-9" '
     || ',Case when mnths_DTV_tenure_band = ''C.10-12'' then 1 else 0 end as  "mnths_dtv_tenure_band C.10-12" '
     || ',Case when DTV_Product_Holding = ''Box Sets'' then 1 else 0 end as  "DTV_Product_Holding Box Sets" '
     || ',Case when DTV_Product_Holding = ''Original'' then 1 else 0 end as  "DTV_Product_Holding Original" '
     || ',Case when DTV_Product_Holding = ''Original (Legacy 2017)'' then 1 else 0 end as  "DTV_Product_Holding Original (Legacy 2017)" '
     || ',Case when DTV_Product_Holding = ''Original (Legacy)'' then 1 else 0 end as  "DTV_Product_Holding Original (Legacy)" '
     || ',Case when DTV_Product_Holding = ''Sky Entertainment'' then 1 else 0 end as  "DTV_Product_Holding Sky Entertainment" '
     || ',Case when DTV_Product_Holding = ''Sky Q'' then 1 else 0 end as  "DTV_Product_Holding Sky Q" '
     || ',Case when ta_call_recency_in_week = ''A.0 NO'' then 1 else 0 end as  "ta_call_recency_in_week A.0 NO" '
     || ',Case when ta_call_recency_in_week = ''B.0 OO'' then 1 else 0 end as  "ta_call_recency_in_week B.0 OO" '
     || ',Case when ta_call_recency_in_week = ''C.1'' then 1 else 0 end as  "ta_call_recency_in_week C.1" '
     || ',Case when ta_call_recency_in_week = ''D.2-3'' then 1 else 0 end as  "ta_call_recency_in_week D.2-3" '
     || ',Case when ta_call_recency_in_week_No_call = 1 then 1 else 0 end as  "ta_call_recency_in_week E.None" '
     || ',Case when  DTV_contract_end_band = ''A.Expiring 6+'' then  1 else 0 end as "dtv_contract_end_band A.Expiring 6+" '
     || ',Case when  DTV_contract_end_band = ''B.Expiring 4-5'' then  1 else 0 end as "dtv_contract_end_band B.Expiring 4-5" '
     || ',Case when  DTV_contract_end_band = ''C.Expiring 2-3'' then  1 else 0 end as "dtv_contract_end_band C.Expiring 2-3" '
     || ',Case when  DTV_contract_end_band = ''D.Expiring 1'' then  1 else 0 end as "dtv_contract_end_band D.Expiring 1" '
     || ',Case when  DTV_contract_end_band = ''E.Expired 1'' then  1 else 0 end as "dtv_contract_end_band E.Expired 1" '
     || ',Case when  DTV_contract_end_band = ''F.Expired 2-5'' then  1 else 0 end as "dtv_contract_end_band F.Expired 2-5" '
     || ',Case when  DTV_contract_end_band = ''G.Expired 6-8'' then  1 else 0 end as "dtv_contract_end_band G.Expired 6-8" '
     || ',Case when  BB_contract_end_band = ''A.Expiring 6+'' then  1 else 0 end as "bb_contract_end_band A.Expiring 6+" '
     || ',Case when  BB_contract_end_band = ''B.Expiring 4-5'' then  1 else 0 end as "bb_contract_end_band B.Expiring 4-5" '
     || ',Case when  BB_contract_end_band = ''C.Expiring 2-3'' then  1 else 0 end as "bb_contract_end_band C.Expiring 2-3" '
     || ',Case when  BB_contract_end_band = ''D.Expiring 1'' then  1 else 0 end as "bb_contract_end_band D.Expiring 1" '
     || ',Case when  BB_contract_end_band = ''E.Expired 1'' then  1 else 0 end as "bb_contract_end_band E.Expired 1" '
     || ',Case when  BB_contract_end_band = ''F.Expired 2-5'' then  1 else 0 end as "bb_contract_end_band F.Expired 2-5" '
     || ',Case when  BB_contract_end_band = ''G.Expired 6-8'' then  1 else 0 end as "bb_contract_end_band G.Expired 6-8" '
     || ',Case when h_affluence=''Very High'' then 1 else 0 end as "affluence_band C.Very H" '
     || ',Case when h_affluence=''Very Low'' then 1 else 0 end as "affluence_band D.Very L" '
     || ',Case when Regr_Prems_Product_Holding= ''Basic''  then 1 else 0 end as "Prems_Product_Holding Basic"'
     || ',Case when Regr_Prems_Product_Holding= ''Movies'' then 1 else 0 end as "Prems_Product_Holding Movies"'
     || ',Case when Regr_Prems_Product_Holding= ''Sports'' then 1 else 0 end as "Prems_Product_Holding Sports"'
     || ',Case when Regr_Prems_Product_Holding= ''Top Tier'' then 1 else 0 end as "Prems_Product_Holding Top Tier"'
     || case when "TA_Forecast_Model" is not null then "TA_Propensity_SQL" end
     || case when "Value_Forecast_Model" is not null then "Value_Propensity_SQL" end
     || case when "Value_Forecast_Model" is not null then ',bws.Seasonality_Multiplier Value_Call_Seasonality_Multiplier ' end
     || case when "Value_Forecast_Model" is not null then ',Value_propensity_Unadjusted * Value_Call_Seasonality_Multiplier as Value_propensity ' end;
  execute immediate "Dynamic_SQL" || ' from ' || "Src_Table" || ' as A '
     || case when "TA_Forecast_Model" is not null then ' left join '
       || ' Decisioning.FORECAST_TA_Propensity_Variables as cpv_TA '
       || ' on cpv_TA.Forecast_Model = ''' || "TA_Forecast_Model" || ''''
       || case when "TA_Forecast_Model" = 'Actuals' then ' and cpv_TA.Subs_Week_and_year = A.Fcast_Subs_Week_And_Year ' end end
     || case when "Value_Forecast_Model" is not null then ' left join '
       || ' Decisioning.FORECAST_Value_Propensity_Variables as cpv_Value '
       || ' on cpv_Value.Forecast_Model = ''' || "Value_Forecast_Model" || ''''
       || case when "Value_Forecast_Model" = 'Actuals' then ' and cpv_Value.Subs_Week_and_year = A.Fcast_Subs_Week_And_Year ' end end
     || 'inner join '
     || 'Fcast_Seasonality_Adjustments as seasonality '
     || 'on seasonality.subs_week = ' || case when "TA_Forecast_Model" = 'Actuals' then 'A.Fcast_Subs_Week_And_Year ' else 'A.Subs_Week_And_Year ' end || ' % 100 ';
  commit work;
  if "Proc_Function" = 'Scoring' then
    set "Dynamic_SQL"
       = ' Update Forecast_Loop_Table base '
       || ' Set ' || case when "TA_Forecast_Model" is not null then "Trgt_TA_Score_Field" || ' = trgt.ta_propensity,' end
       || case when "Value_Forecast_Model" is not null then "Trgt_Value_Score_Field" || ' = trgt.value_propensity,' end;
    if "right"("Dynamic_SQL",1) = ',' then
      execute immediate "Substr"("Dynamic_SQL",1,"len"("Dynamic_SQL")-1)
         || ' from ' || current user || '.' || "Trgt_View_Name" || ' as trgt'
         || ' where trgt.account_number = base.account_number '
         || '       and trgt.end_date = base.end_date '
         || '       and base.DTV_Active = 1 '
    end if
  end if
end
